language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    # let's start simple:
    - PYTHON_VERSION="3.9" LATEST="true"
    - PYTHON_VERSION="3.10" COVERAGE="true" LATEST="true"
    - PYTHON_VERSION="3.11" LATEST="true"
install: source ./ci/.travis_install.sh
script: bash ./ci/.travis_test.sh
after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache: apt
sudo: false
